name: 自动拉取最新博文

on:
  workflow_dispatch:
    push:
      branches:
        - main
    schedule:
      - cron: "15 0 * * *" # 每天 0:15 时运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Update README
        run: |-
          python gen_readme.py
          cat README.md
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "yrzx404@gmail.com"
          git config --global user.name "yrzx404"
          git pull
          git add -A
          git commit -m "Updated README content `date`" || exit 0
          git push
        env:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
